lowlydba/lowlydba.sqlserver

- plugins/module_utils/_SqlServerUtils.psm1
- plugins/modules/nonquery.ps1
When in checkmode, execute the query in NOEXEC mode to get compile and parse checking.
> add noexec for checkmode

- .github/workflows/ansible-test.yml
- README.md
- plugins/module_utils/_SqlServerUtils.psm1
- plugins/modules/agent_job_category.ps1
- plugins/modules/agent_job_category.py
- plugins/modules/agent_job_schedule.ps1
- plugins/modules/agent_job_schedule.py
- tests/integration/targets/agent_job_category/tasks/main.yml
- tests/integration/targets/agent_job_schedule/aliases
- tests/integration/targets/agent_job_schedule/meta/main.yml
- tests/integration/targets/agent_job_schedule/tasks/main.yml
Add a module for SQL Agent job schedules.
This module uses `Format-JsonOutput` instead of `ConvertTo-HashTable`. I'll work on converting existing modules to use JSON output and remove the HashTable approach since this is much cleaner.
Half-implemented integration tests.
> Add agent schedule module

- .github/workflows/github-release.yml
A way to create a nice GitHub release easily, after the actual release process.
It's a manual run, to be done after it's published to galaxy.
community.hashi_vault
> add GH release workflow

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
- .github/workflows/docs-pr.yml
- .github/workflows/docs-push.yml
Adding docs builds on push and PR. There's no publish step yet for these, so this does the following for now:
* on push: ensures docs can be built without errors
* on PR:
* ensures docs build without errors
* performs a lenient build on both the PR base and target, compares them, and if there are differences, posts a comment on the PR highlighting the differences
* when a publishing step is included (future), the comment can include links to these pages
* the built docsite can be downloaded from the build artifacts to be inspected locally
UPDATE on below:
- PR flows tested in #41 
- Push tested in https://github.com/lowlydba/lowlydba.sqlserver/actions/runs/2045703922
----
The push workflow only triggers on pushes to `main`, and the PR workflow uses the `pull_request_target` event which …
> docs-build first pass

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
- changelogs/fragments/62-agent-category-consistency.yml
- plugins/modules/agent_job_category.ps1
- tests/integration/targets/agent_job/tasks/main.yml
This should make the agent job category tests no longer fail on the first try.
> agent_job_category: increase result consistency

- .github/workflows/ansible-test-windows.yml
Latest version of mssqlsuite sets the memory during install, so we can skip the discrete step!
> CI: Update to set memory during install

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
- changelogs/fragments/83-fix-agent-schedule.yml
- plugins/modules/agent_job_schedule.ps1
- plugins/modules/agent_job_schedule.py
- tests/integration/targets/agent_job_schedule/tasks/main.yml
Removes opinionated default value for 'enabled' and fixes inability to *actually* enable a schedule
Added new test
> fix schedule enabling

- changelogs/fragments/95-fix-agent-job-step-removal.yml
- plugins/modules/agent_job_step.ps1
- plugins/modules/agent_job_step.py
- tests/integration/targets/agent_job_step/tasks/main.yml
Allow job steps to be dropped from ID only, not by name.
Incorporated this into the existing int tests.
> agent_job_step: allow step dropping with id only

- plugins/modules/memory.ps1
- tests/integration/targets/memory/tasks/main.yml
Fix so that dynamically set memory does not get marked as changed when it hasn't changed
Added int test
> fix memory change detection

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/127-fix-doc-check.yml
- galaxy.yml
- plugins/modules/ag_replica.ps1
- plugins/modules/agent_job_schedule.ps1
- plugins/modules/agent_job_step.ps1
- plugins/modules/availability_group.ps1
- plugins/modules/install_script.ps1
- plugins/modules/maintenance_solution.ps1
Fix new sanity check error on dlevel - https://github.com/ansible-collections/news-for-maintainers/issues/25#issuecomment-1301258181
> sanity: fix new dlevel check fails

- changelogs/fragments/xpdirtree_sql_mi_bugfix.yml
- plugins/modules/restore.ps1
- plugins/modules/restore.py
Remove the default option for xpDirTree to allow for compatibility with Azure SQL MI
Not tested
> feature: sql mi compatibility

- changelogs/fragments/fix_doc_example.yml
- plugins/modules/credential.py
Fixes an error in the examples in the credential documentation
N/A
> fix: mismatched param in example

- changelogs/fragments/fix_doc_example.yml
- changelogs/fragments/fix_sa.yml
- plugins/modules/login.ps1
Changed incorrect references of $sa variable to $existingLogin in Login.ps1.  Bug described in #159 
N/A
> fix: change $sa to $existingLogin

- .github/workflows/ansible-test-windows.yml
Add a retry when trying to install collection dependencies, since Galaxy can be pretty flakey.
Fixes #165
> chores: add win ci retry for coll dependency

- .github/workflows/ansible-test-windows.yml
As recommended by Github support, since our calls to install sp_whoisactive are unauthenticated the CI is triggering rate limits (60/hr) so staggering the Windows CI may help alleviate this.
> chores: stagger win ci schedule

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
- README.md
- meta/runtime.yml
Since 2.11 is [EOL](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html) we don't need to be running tests against it.
> chores: remove core 2.11 support/testing

- changelogs/fragments/198-add-onlyaccessible-param-to-database.yml
- galaxy.yml
- plugins/modules/database.ps1
- plugins/modules/database.py
Adds _only_accessible_ parameter to module to support removing orphaned database on availability group replica.
Local testing
This may be difficult to emulate with current infrastructure.
> Fixes #198, adds param to support removing inaccessible databases

- changelogs/fragments/200-remove-dbadatabase-exception-handling.yml
- plugins/modules/database.ps1
Adds conditional handling of result of Remove-DbaDatabase
Errors are not thrown for all failure scenarios
Yes, locally
> Fixes#200 no exception error handling during absent state

- changelogs/fragments/209-fix-port-ref.yml
- changelogs/fragments/release-summary-2-2-2.yml
- galaxy.yml
- plugins/modules/ag_listener.ps1
Make sure we're comparing a property that is actually returned from the listener getter
We don't have AG tests due to the complexity at this time.
> fix: refer to portnumber property correctly

- changelogs/fragments/214-fix-schedule-activestartdate.yml
- plugins/modules/agent_job_schedule.ps1
Add ActiveStartDate to the compare properties so this item is marked accurately as changed.
> Issue-214: Add ActiveStartDate to compare property

- changelogs/fragments/219-spn-format-fix.yml
- plugins/modules/spn.ps1
Updated the backslash to a forward-slash for the $spn var
Fixes the same error outlined [here](https://github.com/dataplat/dbatools/issues/4819)
Tested on local environment with AD
> fixes #218

- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- galaxy.yml
- plugins/modules/install_script.ps1
- plugins/modules/install_script.py
- tests/integration/targets/setup_sqlserver/vars/main.yml
Add new input value to make compatible with dbops v0.9
N/A
-  [x] New feature (non-breaking change which adds functionality)
> feat: add compatibility for dbops v0.9

- changelogs/fragments/245-ag_listener-ip_address-fix.yml
- plugins/modules/ag_listener.ps1
- plugins/modules/ag_listener.py
- plugins/modules/spn.py
- tests/integration/targets/win_ag_listener/tasks/main.yml
changing spec options, ip_address parameter is being changed from a 'str' type to a 'list' type
fixes issue #245
validated the change using a local collection of lowlydba and was able to successfully create a multi subnet ag listener when the ip_address parameter was expecting a list
- [x ] Bug fix (non-breaking change which fixes an issue) - Fixes #
- [x ] I have read/followed the [**CONTRIBUTING**](https://github.com/LowlyDBA/lowlydba.sqlserver/blob/main/CONTRIBUTING.md) document.
- [x ] I have read/followed the [PR Quick Start Guide](https://docs.ansible.com/ansible/devel/community/create_pr_quick_start.html)
- [x ] I have added tests to cover my changes or they are N/A.
- [x ] I have added a [changelog fragment](https://github.com/ansible-community/antsibull-changelog/blob/main/docs/ch …
> changing ip_address param to expect list

- .github/workflows/ansible-test-windows.yml
Fix broken dlevel tests. This ended up being a bit more involved than expected:
* Upgrade wsl to use Ubuntu 24
* Remove auto-update of Ubuntu packages, updating `systemd` in (WSL1, Ubuntu 24) errors out 
* Remove ansible core versions that are no longer in support
* Add ansible core versions that are in support
> chore: use newer python for dlevel

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- plugins/modules/restore.ps1
- tests/integration/targets/win_restore/tasks/main.yml
There is some contextual info that is relevant for debugging database restores that only appears as warning logs in dbatools, thereby not making it natively accessible to Ansible. 
Append the warnings for the restore command to the failure json to increase usability.
> fix: Include warnings for restore failures

- .github/workflows/ansible-test.yml
- README.md
Remove testing for EOL ansible versions
> chore: remove EOL versions

- CHANGELOG.rst
- changelogs/changelog.yaml
- plugins/modules/login.ps1
- tests/integration/targets/login/tasks/main.yml
When creating a login, the login should still be created even if `skip_password_reset` is true.
Incorporated into test
> fix: create login properly when skip reset set

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- plugins/doc_fragments/288-fix-agent-schedule.yml
- plugins/modules/agent_job_schedule.ps1
- tests/integration/targets/agent_job_schedule/tasks/main.yml
Fix error when attempting to create a new job schedule with `enabled` as true.
> fix: dont error with enable on create

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
- README.md
Add version 2.18 explicitly to the test matrixes in GitHub.
> chore: add ansible 2.18 to test matrix

- .github/workflows/ansible-test-windows.yml
Bump to the latest major version of the WSL action used to setup Windows test workflows.
At this time, using the newly enabled WSL2 is problematic (efforts to make it work: https://github.com/lowlydba/lowlydba.sqlserver/pull/284) so we will keep WSL1 to at least get the updated version in place.
> chore: bump vampire wsl GHA to v4

- .github/workflows/ansible-test.yml
Github action runner python version alignment used in sanity checks was out of date upstream. This updates the version to the recently released runner version.
Run through github actions, seems to fix it in my repo.
> update githubaction runner version to 1.17 to fix python errors in sanity checks

- changelogs/fragments/remove-six-usage.yml
- tests/integration/targets/setup_sqlserver_test_plugins/connection_plugins/local_pwsh.py
Remove use of deprecated ansible python types to pass dlevel sanity tests.
> fix: remove use of deprecated ansible python types
