- .github/in-solidarity.yml
- tests/integration/targets/setup_sqlserver_test_plugins/README.md
- tests/integration/targets/setup_sqlserver_test_plugins/connection_plugins/local_pwsh.py
- tests/integration/targets/setup_sqlserver_test_plugins/module_utils/Ansible.Basic.cs
- tests/integration/targets/setup_sqlserver_test_plugins/module_utils/Ansible.ModuleUtils.AddType.psm1
- tests/integration/targets/setup_sqlserver_test_plugins/shell_plugins/pwsh.py
- tests/integration/targets/success_placeholder/meta/main.yml
Add pwsh plugins to allow for integration tests to run on non-Windows runners. This should keep things cleaner on the CI side of things.
> add pwsh plugin redux

- .github/workflows/ansible-test.yml
Fixes #6 since the upstream issue in ansible has been resolved.
> re-enable validate-modules

- README.md
- plugins/modules/sp_configure.ps1
- plugins/modules/sp_configure.py
- tests/integration/targets/sp_configure/aliases
- tests/integration/targets/sp_configure/meta/main.yml
- tests/integration/targets/sp_configure/tasks/main.yml
Add a module to run sp_configure configuration commands
Sanity & integration
> add sp_configure module

- README.md
- plugins/doc_fragments/sql_credentials.py
- plugins/module_utils/_SqlServerUtils.psm1
- plugins/modules/maintenance_solution.ps1
- plugins/modules/maintenance_solution.py
- tests/integration/targets/maintenance_solution/aliases
- tests/integration/targets/maintenance_solution/meta/main.yml
- tests/integration/targets/maintenance_solution/tasks/main.yml
Add a new module to install/update ola's maintenance solution
Local + Int tests
> add maintenance_solution module

- .github/workflows/ansible-test.yml
- README.md
- plugins/module_utils/_SqlServerUtils.psm1
- plugins/modules/database.ps1
- plugins/modules/database.py
- tests/integration/targets/database/aliases
- tests/integration/targets/database/meta/main.yml
- tests/integration/targets/database/tasks/main.yml
Add a database module.
Integration tests! 🎉
> Add database module

- README.md
- plugins/modules/traceflag.ps1
- plugins/modules/traceflag.py
- tests/integration/targets/traceflag/aliases
- tests/integration/targets/traceflag/meta/main.yml
- tests/integration/targets/traceflag/tasks/main.yml
Add a new module for traceflag setting
> add traceflag module

- README.md
- plugins/modules/sp_whoisactive.ps1
- plugins/modules/sp_whoisactive.py
- plugins/modules/traceflag.py
- tests/integration/targets/sp_whoisactive/aliases
- tests/integration/targets/sp_whoisactive/meta/main.yml
- tests/integration/targets/sp_whoisactive/tasks/main.yml
Add a module to install/update sp_whoisactive.
Integration tests
> Add whoisactive module

- README.md
- plugins/modules/agent_job_category.ps1
- plugins/modules/agent_job_category.py
- tests/integration/targets/agent_job_category/aliases
- tests/integration/targets/agent_job_category/meta/main.yml
- tests/integration/targets/agent_job_category/tasks/main.yml
Add module for SQL Agent job categories.
Integration tests
> add agent_job_category module + int tests

- plugins/module_utils/_SqlServerUtils.psm1
- plugins/modules/agent_job_category.ps1
- plugins/modules/agent_job_schedule.ps1
- plugins/modules/database.ps1
- plugins/modules/maintenance_solution.ps1
- plugins/modules/memory.ps1
- plugins/modules/nonquery.ps1
- plugins/modules/resource_governor.ps1
- plugins/modules/sp_configure.ps1
- plugins/modules/sp_whoisactive.ps1
- plugins/modules/traceflag.ps1
Used shared functions for:
* Auth spec
* SqlCredential building
To reduce duplication & make future changes easier to manage.
Existing tests
> use standard functions for repeated code blocks

- README.md
- plugins/module_utils/_SqlServerUtils.psm1
- plugins/modules/agent_job.ps1
- plugins/modules/agent_job.py
- plugins/modules/agent_job_category.py
- plugins/modules/database.ps1
- plugins/modules/maintenance_solution.ps1
- tests/integration/targets/agent_job/aliases
- tests/integration/targets/agent_job/meta/main.yml
- tests/integration/targets/agent_job/tasks/main.yml
- tests/integration/targets/database/tasks/main.yml
- tests/integration/targets/maintenance_solution/tasks/main.yml
- tests/integration/targets/setup_sqlserver/vars/main.yml
Add module for agent_job
I N T E G R A T I O N
> add sql_agent module

- .github/PULL_REQUEST_TEMPLATE.md
- .github/codecov.yml
- README.md
- plugins/modules/agent_job_schedule.ps1
- plugins/modules/agent_job_schedule.py
- plugins/modules/agent_job_step.ps1
- plugins/modules/agent_job_step.py
- tests/integration/targets/agent_job_step/aliases
- tests/integration/targets/agent_job_step/meta/main.yml
- tests/integration/targets/agent_job_step/tasks/main.yml
- tests/integration/targets/win_agent_job_step/aliases
- tests/integration/targets/win_agent_job_step/meta/main.yml
Add a module for agent job steps.
Integration tests!
> Add agent job step module

- .vscode/settings.json
- plugins/modules/agent_job_schedule.ps1
- tests/integration/targets/agent_job_schedule/tasks/main.yml
Enable tests for agent job schedule
> enable agent job sched tests

- README.md
- plugins/module_utils/_SqlServerUtils.psm1
- plugins/modules/login.ps1
- plugins/modules/login.py
- tests/integration/targets/login/aliases
- tests/integration/targets/login/meta/main.yml
- tests/integration/targets/login/tasks/main.yml
- tests/integration/targets/win_login/aliases
- tests/integration/targets/win_login/meta/main.yml
Add login module 🎉 
U-U-Unit tests
> Add login module

- README.md
- plugins/modules/rg_resource_pool.ps1
- plugins/modules/rg_resource_pool.py
- tests/integration/targets/rg_resource_pool/aliases
- tests/integration/targets/rg_resource_pool/meta/main.yml
- tests/integration/targets/rg_resource_pool/tasks/main.yml
- tests/integration/targets/win_rg_resource_pool/aliases
- tests/integration/targets/win_rg_resource_pool/meta/main.yml
Add module for resource governor resource pool
> add rg resource pool module

- .github/workflows/ansible-test-windows.yml
- README.md
- plugins/doc_fragments/state.py
- plugins/module_utils/_SqlServerUtils.psm1
- plugins/modules/agent_job.ps1
- plugins/modules/agent_job.py
- plugins/modules/agent_job_category.ps1
- plugins/modules/agent_job_category.py
- plugins/modules/agent_job_schedule.ps1
- plugins/modules/agent_job_schedule.py
- plugins/modules/agent_job_step.py
- plugins/modules/database.ps1
- plugins/modules/database.py
- plugins/modules/login.ps1
- plugins/modules/login.py
- plugins/modules/rg_resource_pool.ps1
- plugins/modules/rg_resource_pool.py
- plugins/modules/rg_workload_group.ps1
- plugins/modules/rg_workload_group.py
- tests/integration/targets/rg_workload_group/aliases
- tests/integration/targets/rg_workload_group/meta/main.yml
- tests/integration/targets/rg_workload_group/tasks/main.yml
- tests/integration/targets/setup_sqlserver/vars/main.yml
- tests/integration/targets/win_rg_workload_group/aliases
- tests/integration/targets/win_rg_workload_group/meta/main.yml
Adds a resource governor workload group module
Also some minor improvements on doc fragments, object re-use, and updating to the latest dbatools version for a parameter fix.
int tests
> Add workload group

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- plugins/modules/agent_job.py
- plugins/modules/agent_job_category.py
- plugins/modules/agent_job_schedule.py
- plugins/modules/agent_job_step.py
- plugins/modules/database.py
- plugins/modules/login.py
- plugins/modules/maintenance_solution.py
- plugins/modules/memory.py
- plugins/modules/nonquery.py
- plugins/modules/resource_governor.py
- plugins/modules/rg_resource_pool.py
- plugins/modules/rg_workload_group.py
- plugins/modules/sp_configure.py
- plugins/modules/sp_whoisactive.py
- plugins/modules/traceflag.py
Ready for v0.1.0 to publish to Ansible Galaxy!
> First release

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
> add galaxy db tag

- .github/workflows/ansible-test-windows.yml
- changelogs/fragments/48-cleanup-utils.yml
- plugins/module_utils/_SqlServerUtils.psm1
- plugins/modules/agent_job.ps1
- plugins/modules/agent_job_category.ps1
- plugins/modules/agent_job_schedule.ps1
- plugins/modules/agent_job_step.ps1
- plugins/modules/database.ps1
- plugins/modules/login.ps1
- plugins/modules/maintenance_solution.ps1
- plugins/modules/memory.ps1
- plugins/modules/nonquery.ps1
- plugins/modules/resource_governor.ps1
- plugins/modules/rg_resource_pool.ps1
- plugins/modules/rg_workload_group.ps1
- plugins/modules/sp_configure.ps1
- plugins/modules/sp_whoisactive.ps1
- plugins/modules/traceflag.ps1
Clean up utils and shared code.
* Utilize `#Requires` for PowerShell module dependency management
* Move TypeArray fix into shared util
* Return instance and creds from credential function
> clean up utils and shared code

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/47-improve-module-documentation.yml
- changelogs/fragments/48-cleanup-utils.yml
> bump version to 0.2.0

- changelogs/fragments/55-fix-login-param.yml
- plugins/modules/login.ps1
- plugins/modules/sa.ps1
- plugins/modules/sa.py
- tests/integration/targets/login/tasks/main.yml
- tests/integration/targets/sa/aliases
- tests/integration/targets/sa/meta/main.yml
- tests/integration/targets/sa/tasks/main.yml
- tests/integration/targets/win_sa/aliases
- tests/integration/targets/win_sa/meta/main.yml
Add a module for hardening the sa login.
Also a bug fix for the login module.
Do not merge until https://github.com/dataplat/dbatools/pull/8289 is landed & the LoginName/Name defaults in the integration tests can be cleaned up.
> Add sa module

- .github/workflows/ansible-test-windows.yml
- README.md
- changelogs/fragments/56-test-for-login-name.yml
- plugins/modules/agent_job.ps1
- plugins/modules/agent_job_category.ps1
- plugins/modules/agent_job_schedule.ps1
- plugins/modules/agent_job_step.ps1
- plugins/modules/database.ps1
- plugins/modules/instance_info.ps1
- plugins/modules/login.ps1
- plugins/modules/maintenance_solution.ps1
- plugins/modules/memory.ps1
- plugins/modules/nonquery.ps1
- plugins/modules/resource_governor.ps1
- plugins/modules/rg_resource_pool.ps1
- plugins/modules/rg_workload_group.ps1
- plugins/modules/sa.ps1
- plugins/modules/sp_configure.ps1
- plugins/modules/sp_whoisactive.ps1
- plugins/modules/traceflag.ps1
- tests/integration/targets/login/tasks/main.yml
- tests/integration/targets/sa/tasks/main.yml
- tests/integration/targets/setup_sqlserver/vars/main.yml
Previously the dbatools login functions would return LoginName/Name as default values, now that it is standardized it can be tested for and return more standardized output.
> Fix login name in integration tests

- .github/workflows/ansible-test-windows.yml
> disable mongodb on runner

- .github/workflows/ansible-test-windows.yml
> update wsl action

- .github/workflows/docs-pr.yml
- .github/workflows/docs-push.yml
- .github/workflows/github-release.yml
- Simplify the PR validate workflow
- https://github.com/ansible-community/github-docs-build/pull/45
- Add GitHub Pages publishing so we can have a rendered docsite 🎉 
- https://github.com/ansible-community/github-docs-build/pull/44
Testing done on a fork I had of another collection, and testing done on my collection as well (https://github.com/ansible-collections/community.hashi_vault/pull/261).
> docs-build github pages publish

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
- README.md
- changelogs/fragments/70-deprecate-ansible-2.10.yml
- plugins/modules/ag_listener.ps1
- plugins/modules/ag_listener.py
- tests/integration/targets/win_ag_listener/aliases
- tests/integration/targets/win_ag_listener/meta/main.yml
- tests/integration/targets/win_ag_listener/tasks/main.yml
Add new availability group listener module.
> add ag_listener module

- plugins/modules/ag_replica.ps1
- plugins/modules/ag_replica.py
- tests/integration/targets/win_ag_replica/aliases
- tests/integration/targets/win_ag_replica/meta/main.yml
- tests/integration/targets/win_ag_replica/tasks/main.yml
Add a module for ag replica configuration.
Pretty not-confident in being able to test any of this with a single replica, but we'll see..
> Add ag replica module

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
> bump version to 0.6.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- plugins/modules/dba_multitool.ps1
- plugins/modules/dba_multitool.py
- tests/integration/targets/dba_multitool/aliases
- tests/integration/targets/dba_multitool/meta/main.yml
- tests/integration/targets/dba_multitool/tasks/main.yml
- tests/integration/targets/win_dba_multitool/aliases
- tests/integration/targets/win_dba_multitool/meta/main.yml
Add a module for Install-DbaMultitool
integration tests
> Add multitool module

- .github/dependabot.yml
- .github/workflows/ansible-test-windows.yml
Make the CI more robust and get notified of out of date gha
> gh action updates, mssql retries

- plugins/modules/availability_group.ps1
- plugins/modules/availability_group.py
- plugins/modules/backup.ps1
- plugins/modules/backup.py
- plugins/modules/database.py
- plugins/modules/dba_multitool.py
- plugins/modules/maintenance_solution.py
- plugins/modules/sp_whoisactive.py
- tests/integration/targets/backup/aliases
- tests/integration/targets/backup/meta/main.yml
- tests/integration/targets/backup/tasks/main.yml
- tests/integration/targets/win_backup/aliases
- tests/integration/targets/win_backup/meta/main.yml
Add backup module
Integration tests
> Back-it-up

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/105-update-dbatools-version.yml
- galaxy.yml
> version bump

- .github/workflows/ansible-test.yml
> chore: update ci python version

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/resource_governor.yml
- galaxy.yml
> 1.0.1 release

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
https://github.com/ansible-collections/news-for-maintainers/issues/24
> chores: test against ansible 2.14

- README.md
Update readme to reflect latest versions tested against
> chores: add 2.14 test version

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
Start testing against SQL Server 2022 by default
> chores: test against sql server 2022

- .github/workflows/ansible-test.yml
Fix build issues: https://github.com/ansible-collections/news-for-maintainers/issues/28
> chores: fix ci issues with older ubuntu

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- changelogs/fragments/xpdirtree_sql_mi_bugfix.yml
- galaxy.yml
> v1.1.2 bump

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/reuse_source_folder_structure_sql_mi_bugfix.yml
- galaxy.yml
> v1.1.3 bump

- .github/workflows/release.yml
> chores: publish to galaxy + update gh release action

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/additional_sql_mi_fixes.yml
- galaxy.yml
> 1.2.1 bump

- .github/workflows/ansible-test.yml
build issues resolved: https://github.com/ansible-collections/news-for-maintainers/issues/28
> chores: unpin ubuntu version

- changelogs/fragments/167-update-login-docs.yml
- changelogs/fragments/xx-update-login-docs.yml
- plugins/modules/login.py
Note that module will always show changed when password is given.
> Login: note password behavior

- changelogs/fragments/185-fix-agent-schedule.yml
- plugins/modules/agent_job_schedule.ps1
- tests/integration/targets/agent_job_schedule/tasks/main.yml
Add a workaround to manually refresh the agent schedule.
> add workaround for agent_schedule bug

- plugins/modules/sa.py
Example on sa module used disable: true instead of enabled: false
Fixes lowlydba/lowlydba.sqlserver#188
n/a
> Issue-188: Fix example in sa module

- changelogs/fragments/2-1-0-release.yml
> build: add release summary

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/198-add-onlyaccessible-param-to-database.yml
> chore: release 2.2.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/200-remove-dbadatabase-exception-handling.yml
- galaxy.yml
> chore: bump to v2.2.1

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
Add stable 2.16 to test matrix
> chore: update test matrix

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/209-fix-port-ref.yml
- changelogs/fragments/214-fix-schedule-activestartdate.yml
- changelogs/fragments/219-spn-format-fix.yml
- changelogs/fragments/release-summary-2-2-2.yml
- galaxy.yml
> chore: version bump

- .github/workflows/ansible-test-windows.yml
- tests/integration/targets/win_ag_replica/tasks/main.yml
> fix: remove unsafe assertion

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- plugins/modules/agent_job_schedule.py
- tests/integration/targets/agent_job_schedule/tasks/main.yml
Fix the docs to reflect the correct date syntax needed for inputs.
> fix: update docs and add test case

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/245-ag_listener-ip_address-fix.yml
- galaxy.yml
Version bump for release v2.3.3
> chore: bump to v2.3.3

- .github/workflows/ansible-test.yml
> chore: remove EOL version testing

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- plugins/modules/user_role.ps1
- plugins/modules/user_role.py
- tests/integration/targets/user_role/aliases
- tests/integration/targets/user_role/meta/main.yml
- tests/integration/targets/user_role/tasks/main.yml
- tests/integration/targets/win_restore/tasks/main.yml
- tests/integration/targets/win_user_role/aliases
- tests/integration/targets/win_user_role/meta/main.yml
Add a new module to map users to database roles.
New tests added for the module. A little sparse since DBATools doesn't return output for most of these operations, and the current philosophy has been to just echo DBATools' output rather than create our own outputs to make sure that working natively with DBATools and this collection stays behaving the same.
> feat: add user_role module

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- plugins/modules/login_role.ps1
- plugins/modules/login_role.py
- tests/integration/targets/login_role/aliases
- tests/integration/targets/login_role/meta/main.yml
- tests/integration/targets/login_role/tasks/main.yml
- tests/integration/targets/win_login_role/aliases
- tests/integration/targets/win_login_role/meta/main.yml
Add a module to allow adding and removing logins from server roles.
New tests added for the role.
> feat: Add server role module

- CHANGELOG.rst
- galaxy.yml
- plugins/modules/availability_group.py
> chore: v2.6.0

- .github/workflows/ansible-test-windows.yml
- .github/workflows/ansible-test.yml
- CHANGELOG.rst
- README.md
- changelogs/changelog.yaml
- galaxy.yml
- tests/integration/targets/agent_job/tasks/main.yml
- tests/integration/targets/agent_job_category/tasks/main.yml
- tests/integration/targets/agent_job_schedule/tasks/main.yml
- tests/integration/targets/agent_job_step/tasks/main.yml
- tests/integration/targets/backup/tasks/main.yml
- tests/integration/targets/credential/tasks/main.yml
- tests/integration/targets/database/tasks/main.yml
- tests/integration/targets/install_script/tasks/main.yml
- tests/integration/targets/login/tasks/main.yml
- tests/integration/targets/memory/tasks/main.yml
- tests/integration/targets/rg_resource_pool/tasks/main.yml
- tests/integration/targets/rg_workload_group/tasks/main.yml
- tests/integration/targets/sp_whoisactive/tasks/main.yml
- tests/integration/targets/traceflag/tasks/main.yml
- tests/integration/targets/user/tasks/main.yml
- tests/integration/targets/user_role/tasks/main.yml
- tests/integration/targets/win_availability_group/tasks/main.yml
- tests/integration/targets/win_install_script/tasks/main.yml
Ensure compatibility with Ansible 2.19, and remove 2.16 as it is EOL this month.
Fixes #313
> chore: add ansible 2.19 to test matrices, remove 2.16

- .github/copilot-instructions.md
- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/329-add-agent-outputfile.yml
- plugins/modules/agent_job_step.ps1
- plugins/modules/agent_job_step.py
- tests/integration/targets/agent_job_step/tasks/main.yml
> feat: add outputfile param for agent job steps
